### ISSUE TITLE
Installation 

### ISSUE THREAD

**Issue by bepolymathe** [EdoFro/Freeplane_Map-Drive-Inator#1]
Hi @EdoFro !

Another great project! Thanks a lot. This is exactly what I'm looking for! 
Before I get started, do you have any installation tips? Do I have to install all the scripts by hand? One by one? Or is there a slightly more automated procedure?
I works under Linux Fedora distribution. 
I can't wait to try ;-)

**Comment by EdoFro** [comment]
Hi @bepolymathe,
nowadays the only way is to install this by hand. 

the mindmap file "Map-Drive-Inator.mm" has all the instructions.

I want to transform this project into an AddOn but I haven't had the time yet. But I will do it.

bye!

**Comment by bepolymathe** [comment]
Great. Thanks for reply. I will try by hand. 
Have a good evening.

**Comment by bepolymathe** [comment]
Hi, 

I try to reinstall Map Drive Inator on other machine and i forget the installation process by hand. Could you remember me ? 
Thanks !

**Comment by EdoFro** [comment]
Hahahaha, I have this problem myself. I haven't installed it in a while. I just copy/paste the whole user directory to other machines. This way I take all scripts, add-ons, preferences, etc to the new machine.

this means that I haven't done the installation process since the first time, so I don't remember.

This is what I remember:
1. the instructions are in the mindmap file "Map-Drive-Inator.mm" (haven't look at them again)
2. you have to copy the MDI.groovy file to the <userdirectory>/lib folder
3. you have to copy all other groovy files to your scripts folder
4. restart freeplane

I wont write better instructions for this version of MDI. I prefer to use my time to transform it to an add-on

regards,

edo

**Comment by EdoFro** [comment]
1. try adding a "/" as last character in the link

example:
![image](https://user-images.githubusercontent.com/35700575/211320512-69f377a8-232c-4811-bc9a-98fe082b06f6.png)

I edit the link:
![image](https://user-images.githubusercontent.com/35700575/211320826-cb5b4b26-90d8-4d20-83fb-b706b77e166b.png)

Now it looks like this:
![image](https://user-images.githubusercontent.com/35700575/211320970-25925a02-c6b6-42d6-a96d-52a70f05c78d.png)

**Comment by bepolymathe** [comment]
Yes i have test it... 

![image](https://user-images.githubusercontent.com/29939805/211324050-15505472-bf4e-4690-a0b3-0eaacc8215a1.png)

The path seems fine and open the right place but i have always the same error message 🤔

**Comment by EdoFro** [comment]
I don't know why, but depending how you paste the path to the node it beheaves different:

look at this example:
there are two "Temp" nodes. Both with the same link, but one gets the conditional styles and the other not.

![image](https://user-images.githubusercontent.com/35700575/211324202-123c431f-aa7e-4bbf-bb27-e8cbfebd328a.png)

The first one:

![image](https://user-images.githubusercontent.com/35700575/211324028-438bcff0-4fc6-4488-af88-db5e61fe4fcc.png)

The second one:

![image](https://user-images.githubusercontent.com/35700575/211324569-b61386e8-e239-4ba0-b0c7-69b7f4654fd0.png)


The first one is going to work ok, and the other is going to throw an error

**Comment by EdoFro** [comment]
You have to assign manually the "file_folder" style to it:
![image](https://user-images.githubusercontent.com/35700575/211325050-b4ae2a48-39a6-4d14-9fcd-2f6c931cb39a.png)

Then it should work

**Comment by EdoFro** [comment]
> Did you drag and drop the first or copy/paste ?

I usually do DragnDrop

**Comment by bepolymathe** [comment]
Oh wait... I just realized that nodes styles are not imported. I forgot to copy / paste something from the repo...

**Comment by bepolymathe** [comment]
Maybe i have to place the "MapDriveInator" folder somewhere ?

![image](https://user-images.githubusercontent.com/29939805/211326686-6abafdac-32b9-4832-969b-613a89e552c7.png)

**Comment by bepolymathe** [comment]
That’s strange... 
Can you show me your scripts config page in the settings ? (tools --» preference --» Formulas et Scripts)

**Comment by bepolymathe** [comment]
Maybe we are back to our [previous discussion](https://sourceforge.net/p/freeplane/discussion/758437/thread/f25fa9a068/?page=3#dfe8) ?

**Comment by bepolymathe** [comment]
Hi @EdoFro 

So ... If I use your Map-Drive-Inator default map I manage to execute "MAP-DRIVE-INATOR" for the first time but if I want to update (execute it again), I have the same error message than before.

[Capture vidéo du 2023-01-10 11-55-31.webm](https://user-images.githubusercontent.com/29939805/211534263-00adeabd-fe17-434c-9e4e-f8ddff3a0c66.webm)

Any idea why ?

**Comment by bepolymathe** [comment]
> Any idea why ?

Can I ping you ? I really want to make it works again...

**Comment by EdoFro** [comment]
I'm going to look at it tonight. My intention is to pack it as an add-on as it is and solve all minor bugs in the next days.

No new functionalities until it works reliably.

**Comment by bepolymathe** [comment]
That’s great. Thanks you so much !

**Comment by EdoFro** [comment]
Hi @bepolymathe,
I just packed it as an add-on.

Here it is:
https://github.com/EdoFro/Freeplane_Map-Drive-Inator/releases

But before installing it, do following steps in your Freeplane installation to be sure this will be the only active version of MDI

-----

Test 1:
- create a new node and write this formula in it :`= MDI.class`
  - if it shows "**class MDI**", it means that MDI is still installed in Freeplane.
  - if it shows **"Error setting the text for the following input: =MDI.class:org.freeplane.plugin.script.ExecuteScriptException: No such property: MDI for class: Script1 at line -1."**

So, in order to be sure you don't have any other MDI scripts, you have to do following steps and repeat Test 1 until it shows an error message.

-----

1. go to: `Preferences…->Plugins->Scripting->Script classpath: Additional directories containing classes and/or JARs (see tooltip)`
   - and look there which directories are defined for libs
   - go to those folders and delete any MDI.groovy file

in my case:
![image](https://user-images.githubusercontent.com/35700575/212978856-21536c85-7092-4dff-a0b9-02b47abb35c2.png)

so I '**opened user directory**' an then I entered the _**lib**_ folder and deleted the **MDI.groovy** file that was there.

----

2. delete all old MDI scripts that are in the scripting folder

3. force a new compilation of the scripts (you can do this or delete the compiled files that you want to refresh)
  (I don't know if this is necessary but I did it to be sure.)
  - uncheck `Preferences…->Plugins->Scripting->Compile only changed files`
 
![image](https://user-images.githubusercontent.com/35700575/212979536-e2ecb6cd-8657-430e-86ed-16e41a6ea129.png)

   - restart Freeplane
   - do Test 1
   - check `Preferences…->Plugins->Scripting->Compile only changed files` back

If Test 1 doesn't recognize MDI anymore, then install the new MDI add-on

Tell me how it goes

**Comment by bepolymathe** [comment]
Ok, no it’s ok. I got the error message...

**Comment by bepolymathe** [comment]
> If Test 1 doesn't recognize MDI anymore, then install the new MDI add-on

For this, i assume i need to copy file from "MapDriveInatorV2" directory ?

**Comment by bepolymathe** [comment]
![Uploading image.png…]()

**Comment by bepolymathe** [comment]
![image](https://user-images.githubusercontent.com/29939805/213014984-bba52cb2-38c5-4012-8848-c7da78fe1f1b.png)

**Comment by EdoFro** [comment]
new release:
https://github.com/EdoFro/Freeplane_Map-Drive-Inator/releases/tag/v0.0.4

![image](https://user-images.githubusercontent.com/35700575/213022489-16ec96d9-79ea-4e44-b968-d897f0854e65.png)

**Comment by EdoFro** [comment]
> > If Test 1 doesn't recognize MDI anymore, then install the new MDI add-on
> 
> For this, i assume i need to copy file from "MapDriveInatorV2" directory ?

I just realize that I didn't upload the v0.0.3 file. Sorry! I did it now, but you can try v0.0.4.

I corrected some issues there too.

**Comment by EdoFro** [comment]
> ![image](https://user-images.githubusercontent.com/29939805/213014984-bba52cb2-38c5-4012-8848-c7da78fe1f1b.png)

That map is the mindmap I use to organize this project, you don't need to look at it if you don't want.

I use multiple styles and scripts in my maps. 

If you want to look at it, for this specific issue, you have to install the following add-on. It's a little one, that helps me see which nodes have scripts in their notes or attributes:

https://github.com/EdoFro/Freeplane_groovyNode

latest release:
https://github.com/EdoFro/Freeplane_groovyNode/releases/latest

**Comment by EdoFro** [comment]
I tested this new MDI add-on on my computer the whole afternoon. I corrected some bugs and published the new version as v0.0.4

As said before I don't want to add new functionalities until we feel it works allways and flawless.

Please report any new issue ASAP so I can correct it now that I managed to understand the code again.

I will close this issue. Please create new ones for the bugs you discover.

Bye
